### ISSUE TITLE
Change names in About - Team Menu

### ISSUE THREAD

**Issue by maiaKord** [maiaKord/small-world-ludumdare#6]

**Comment by Xeoneid** [comment]
Oh es verdad que al final hicimos 2 juegos. Todo ok, haganlo, no me ofendo :)

**Comment by maiaKord** [comment]
@Xeoneid  flasheaste cualquiera.... JAJAJAJA 

Ayer con @gdlneo pensamos que es mejor solo nuestros alias y el que no tiene su nombre o el que quiere poner su nombre en vez de su alias, pero que figure un solo nombre
es como que si ponemos los dos (nombre - alias) parecen dos personas distintas (y a mi particularmente no me gusta que figure mi nombre posta)
con que diga Maia Kord es mas que suficiente, al menos en mi caso
el resto yo diria que elija un solo nombre para que figure
en mi opinion haria esa, no se que opina el resto ?

**Comment by maiaKord** [comment]
Done https://github.com/maiaKord/small-world-ludumdare/commit/498131c582d129e7b39355c9a085460bcbd44e62
